### ISSUE TITLE
mkl_random drop mtrand attributes

### ISSUE THREAD

**Issue by memory-yancy** [IntelPython/mkl_random#2]
Environment:
* docker image: intelpython/intelpython3_full:2018.0.1
----
By look throught some data on the Internet, I use IntelPython to achieve accelerating in `numpy.random` or `numpy.fft`. And, if using `numpy.random_intel`(it will call `mkl_random` indirectly) or `numpy.fft`(also, it will call `numpy.fft_intel indirectly), it will produce a nice result. :+1: 

When I read `numpy.random` and `numpy.random_intel` relevant codes and work principles, I find mkl_random drop attribute `mtrand`.

```
root@d69506027046:/opt/conda# python
Python 3.6.3 |Intel Corporation| (default, Oct 16 2017, 15:28:36) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
... ...
>>> from numpy import random as nr
>>> dir(nr)
['Lock', 'RandomState', '__RandomState_ctor', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_numpy_tester', 'absolute_import', 'bench', 'beta', 'binomial', 'bytes', 'chisquare', 'choice', 'dirichlet', 'division', 'exponential', 'f', 'gamma', 'geometric', 'get_state', 'gumbel', 'hypergeometric', 'info', 'laplace', 'logistic', 'lognormal', 'logseries', 'mtrand', 'multinomial', 'multivariate_normal', 'negative_binomial', 'noncentral_chisquare', 'noncentral_f', 'normal', 'np', 'operator', 'pareto', 'permutation', 'poisson', 'power', 'print_function', 'rand', 'randint', 'randn', 'random', 'random_integers', 'random_sample', 'ranf', 'rayleigh', 'sample', 'seed', 'set_state', 'shuffle', 'standard_cauchy', 'standard_exponential', 'standard_gamma', 'standard_normal', 'standard_t', 'test', 'triangular', 'uniform', 'vonmises', 'wald', 'warnings', 'weibull', 'zipf']

>>> from numpy import random_intel as ni
>>> dir(ni)
['BOXMULLER', 'BOXMULLER2', 'ICDF', 'Lock', 'POISNORM', 'PTPE', 'RandomState', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'absolute_import', 'bench', 'beta', 'binomial', 'bytes', 'chisquare', 'choice', 'choose_method', 'dirichlet', 'division', 'exponential', 'f', 'gamma', 'geometric', 'get_state', 'gumbel', 'hypergeometric', 'laplace', 'logistic', 'lognormal', 'logseries', 'mklrand', 'multinomial', 'multinormal_cholesky', 'multivariate_normal', 'negative_binomial', 'noncentral_chisquare', 'noncentral_f', 'normal', 'np', 'operator', 'pareto', 'permutation', 'poisson', 'power', 'print_function', 'rand', 'randint', 'randn', 'random_integers', 'random_sample', 'rayleigh', 'seed', 'set_state', 'shuffle', 'standard_cauchy', 'standard_exponential', 'standard_gamma', 'standard_normal', 'standard_t', 'test', 'triangular', 'uniform', 'vonmises', 'wald', 'warnings', 'weibull', 'zipf']
>>>   
```

Based on relevant code and installed module, I try to modify code to achieve call `mkl_random` by `numpy.random`.So, file `__init.py`  `99` lines in `numpy/random` is critical.
```
root@d69506027046:/opt/conda/lib/python3.6/site-packages/numpy/random# cat __init__.py 
... ...
 97 with warnings.catch_warnings():
 98     warnings.filterwarnings("ignore", message="numpy.ndarray size changed")
 99     from .mtrand import *
100 

modified line:  from numpy.random_intel import *
... ...
```
Everything is ok in my thought test cases, but since no `mtrand` attribute will fail in `scipy.test(verbose=10)`.If so, it willn't work and accelerating doesn't work ... So, about mtrand, for what reason is it not integrated.  Any help is appreciate !

**Comment by memory-yancy** [comment]
Because of lacking of mtrand, I try to construct it as below following:
``` from .mtrand import *
    
    from ..random_intel import *
    from ..random import mtrand
    from .. import random_intel as intel
    dir(intel).append(mtrand)
```
But it will throw errors when I call sklearn.decomposition.PCA in function parameters:
```ValueError('<mtrand.RandomState object at 0x7f595731f9b0> cannot be used to seed a numpy.random.RandomState instance',) error in function <function bench_skl at 0x7f5950619a28>```

**Comment by oleksandr-pavlyk** [comment]
@memory-yancy `mtrand` is the details of the implementation of `numpy.random` submodule of NumPy. The [randomstate](https://github.com/bashtage/ng-numpy-randomstate) module touted as replacement for `numpy.random` in a future version of NumPy has `mtrand` submodule in it. 

An external package's test that requires existence of `numpy.random.mtrand` just needs to change.

Please bear in mind that `mkl_random` is not fixed-seed bit-wise compatible with `numpy.random`, please see [my response](https://software.intel.com/en-us/forums/intel-distribution-for-python/topic/747598) on IDZ forum, meaning that for the same initial seed set in `mkl_random` and `numpy.random`, the sequence of samples can not be expected to be exactly the same. 

Statistical properties of such sequences are expected to be the same though.

**Comment by memory-yancy** [comment]
@oleksandr-pavlyk Really thanks your reply ! 
> An external package's test that requires existence of numpy.random.mtrand just needs to change.

Well, I have rebuild mkl_random as conda package, modify relevant files(such as: `setup.py`, `mtrand.pyx` ...). That's, I will  use `mkl_random.mtrand` and others required files/directory, conda build is ok and selftest is ok, too.

Based on rebuild mkl_random package, I have configed it, start a Python shell to run:
```
>>> import numpy.random as nr
>>> nr.test(verbose=10)
... ...
ERROR: test_uniform (test_random.TestBroadcast)
----------------------------------------------------------------------
TypeError: must be real number, not list  <=========== As you response in Intel forum, it will transfrom to a vector
```
So, whether MKL library ask mkl_random to use vector/list or not, or any issues? I try transform data type but it failed.

**Comment by memory-yancy** [comment]
@oleksandr-pavlyk  Based on recent research, in a word, `mkl_random` is different from `numpy.random`. I didn't understand fully previoud response ago... thanks your reply patiently, now see belowing reasons:
> one which takes a single seed (implemented in numpy.random.seed, but absent in MKL and hence in numpy.random_intel.seed)

* MKL/mkl_random doesn't implement singe seed

> Even having the same underlying pseudo-random sequence of uint32, numpy.random and numpy.random_intel use different algorithms to generate sequences of floating point numbers, even doubles
 
* some algorithms will have different results

----
See also [Intel forum user draws a conclusion based on Intel response](https://software.intel.com/en-us/forums/intel-distribution-for-python/topic/747598#comment-1914242)
