### ISSUE TITLE
setup.py uses numpy.distutils, which has been removed as of numpy 1.25. 

### ISSUE THREAD

**Issue by cbouss** [IntelPython/mkl_random#30]
setup.py uses numpy.distutils, which has been removed as of numpy 1.25. 
This prevents python 3.12 builds.

**Comment by oleksandr-pavlyk** [comment]
Release v1.2.3 transitioned away from using `numpy.distutils`. Please retest and close

**Comment by oleksandr-pavlyk** [comment]
Closing as fixed.
