### ISSUE TITLE
mkl_random does not define __version__, which makes it impossible to detect bad release 1.0.1

### ISSUE THREAD

**Issue by qwhelan** [IntelPython/mkl_random#7]
Hi,

A downstream library I maintain is impacted by https://github.com/IntelPython/mkl_random/issues/4, but `mkl_random` does not define `__version__` so it is impossible to detect if the installed version is affected or not. My logic to handle the `1.0.1` release must assume any `mkl_random` install is that release, which is suboptimal for all users.

Please consider implementing the `__version__` string as suggested by PEP 396, which would allow downstream library maintainers to treat `mkl_random` with more granularity: https://www.python.org/dev/peps/pep-0396/

Thanks,
Chris

**Comment by oleksandr-pavlyk** [comment]
Thanks @qwhelan 

It defines the `__version__` for some time now: https://github.com/IntelPython/mkl_random/blob/master/mkl_random/_version.py

Resolving
